variable name {}
variable port {}
variable protocol {}
variable name_lb {}
variable internal {}
variable load_balancer_type {}
variable port_lb_l {}
variable protocol_lb_l {}
variable type {}
variable port_lb {}
variable port_lb_attach {}