variable name {}
variable description {}
variable from_port {}
variable to_port {}
variable protocol {}
variable cidr_blocks {}
variable from_port_1 {}
variable to_port_1 {}
variable protocol_1 {}
variable cidr_blocks_1 {}
variable from_port_2 {}
variable to_port_2 {}
variable protocol_2 {}
variable cidr_blocks_2 {}
variable description_db {}
variable name_db {}
variable from_port_db {}
variable to_port_db {}
variable protocol_db {}
variable from_port_sg {}
variable cidr_blocks_sg {}
variable to_port_sg {}
variable protocol_sg {}
